---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: true

- name: Install postfix
  apt:
    name: mailutils
    state: present
  become: true

- name: Configure postfix
  command: dpkg-reconfigure postfix
  become: true
