---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install nginx
  apt:
    name:
      - nginx
      - ufw
    state: present
  become: yes

- name: Update nginx confs
  template: "src=../templates/default-site.conf dest=/etc/nginx/sites-available/default"
  become: yes

- name: Allow http in ufw
  become: yes
  command: ufw allow 'Nginx HTTP'

- name: Allow https in ufw
  become: yes
  command: ufw allow https

- name: Enable default site
  file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default state=link
  notify:
    - restart nginx
  become: yes