---
- name: Create nginx proxy site
  include_role:
    name: create-nginx-config

- name: Create site directory for {{site_name}}
  file:
    path: "{{home_dir}}/sites/{{site_name}}"
    state: directory

- name: Clone repository of {{site_name}}
  command: git clone "{{repo_url}}" "{{home_dir}}/sites/{{site_name}}/code"
  args:
    creates: "{{home_dir}}/sites/{{site_name}}/code"
    
- name: Copy env files for {{site_name}}
  copy:
    src: "{{site_env_dir}}/"
    dest: "{{home_dir}}/sites/{{site_name}}/code"
  
- name: Create deploy script
  template:
    src: ../templates/deploy.sh
    dest: "{{home_dir}}/sites/{{site_name}}/deploy.sh"
    mode: '755'

- name: Setup application cron job for {{site_name}}
  when: with_cron
  cron:
    name: app-{{site_name}}
    job: "cd {{home_dir}}/sites/{{site_name}}/code && scripts/cron"
