---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: install git
  apt:
    name: git
    state: present
  become: yes

- name: configure git user.name
  shell: git config --global user.name "{{git_name}}"

- name: configure git user.email
  shell: git config --global user.email "{{git_email}}"
