---
- name: Install snapd
  apt:
    name: snapd
    state: present
  become: yes

- name: Install certbot using snap
  command: snap install --classic certbot
  become: yes

- name: Prepare the certbot command
  file: src=/snap/bin/certbot dest=/usr/bin/certbot state=link
  become: yes
