---
- name: add apt key for nodesource
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  become: true

- name: add repo for nodesource
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{node_version}} {{ ansible_distribution_release }} main"
    update_cache: true
  become: true

- name: install nodejs
  apt:
    name: nodejs
    state: present
  become: true

- name: Create ~/.npm
  command: mkdir ~/.npm
  args:
    creates: ~/.npm

- name: Configure npm to use ~/.npm
  command: npm config set prefix ~/.npm
